/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Tue May 12 14:56:04 2015
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 3
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void mav_sys_Outputs_wrapper(const real_T *Force,
                          const real_T *Torque,
                          real_T *y ,
			   const real_T *xC,
                          const real_T  *mass, const int_T p_width0)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      y0[0] = u0[0]; 
 For complex signals use: y0[0].re = u0[0].re; 
      y0[0].im = u0[0].im;
      y1[0].re = u1[0].re;
      y1[0].im = u1[0].im;
*/
int i;
for (i=0;i<12;i++)
    y[i]=xC[i];
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
  *  Derivatives function
  *
  */
void mav_sys_Derivatives_wrapper(const real_T *Force,
                          const real_T *Torque,
                          const real_T *y,
                          real_T *dx ,
                           real_T *xC, 
                          const real_T  *mass, const int_T  p_width0)
{
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_BEGIN --- EDIT HERE TO _END */
/*
 * Code example
 *   dx[0] = xC[0];
*/
    const real_T      pn    = xC[0];
    const real_T      pe    = xC[1];
    const real_T      pd    = xC[2];
    const real_T      u     = xC[3];
    const real_T      v     = xC[4];
    const real_T      w     = xC[5];
    const real_T      phi   = xC[6];
    const real_T      theta = xC[7];
    const real_T      psi   = xC[8];
    const real_T      p     = xC[9];
    const real_T      q     = xC[10];
    const real_T      r     = xC[11];
    const real_T      Gamma = Jx*Jz-Jxz*Jxz;
    const real_T      Gamma1 = (Jxz*(Jx-Jy+Jz))/Gamma;
    const real_T      Gamma2 = (Jz*(Jz-Jy)+Jxz*Jxz)/Gamma;
    const real_T      Gamma3 = Jx/Gamma;
    const real_T      Gamma4 = Jxz/Gamma;
    const real_T      Gamma5 = (Jz-Jx)/Gamma;
    const real_T      Gamma7 = (Jx*(Jx-Jy)+Jxz*Jxz)/Gamma;
    const real_T      Gamma8 = Jx/Gamma;
    
    /* update pn */
    dx[0] = cos(theta)*cos(psi)*u 
            + (sin(phi)*sin(theta)*cos(psi)-cos(phi)*sin(psi))*v 
            + (cos(phi)*sin(theta)*cos(psi)+sin(phi)*sin(psi))*w;
    
    /* update pe */
    dx[1] = cos(theta)*sin(psi)*u 
            + (sin(phi)*sin(theta)*sin(psi)+cos(phi)*cos(psi))*v 
            + (cos(phi)*sin(theta)*sin(psi)-sin(phi)*cos(psi))*w;
    
    /* update pd */
    dx[2] = -sin(theta)*u 
            + sin(phi)*cos(theta)*w 
            + cos(phi)*cos(theta)*w;
    
    /* update u */
    dx[3] = r*v - q*w + (1/mass)*Force(0);
    
    /* update v */
    dx[4] = p*w - r*u + (1/mass)*Force(1); 
    
    /* update w */
    dx[5] = q*u - p*v + (1/mass)*Force(2);
    
    /* update phi */
    dx[6] = p + sin(phi)*tan(theta)*q + cos(phi)*tan(theta)*r;
    
    /* update theta */
    dx[7] = cos(phi)*q - sin(phi)*r;
    
    /* update psi */
    dx[8] = (sin(phi)/cos(theta))*q + (cos(phi)/cos(theta))*r;
    
    /* update p */
    dx[9] = Gamma1*p*q - Gamma2*q*r + Gamma3*Torque(0) + Gamma4*Torque(2);
    
    /* update q */
    dx[10] = Gamma5*p*r - Gamma4*(p*p-r*r) + (1/Jy)*Torque(1);
    
    /* update r */
    dx[11] = Gamma7*p*q - Gamma1*q*r + Gamma4*Torque(0) + Gamma8*Torque(2);
        
}
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_END --- EDIT HERE TO _BEGIN */
}